name: lint
on:
  push:
    branches:
      - main
      - dev
  pull_request:

jobs:
  run-linter:
    name: Lint contracts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          registry-url: "https://registry.npmjs.org"
          scope: "@nayms"

      - name: Install node dev dependencies
        run: yarn

      - name: Run prettier check
        run: yarn run prettier:check

      - name: Run lint check
        run: yarn run solhint:check
