name: tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          registry-url: 'https://registry.npmjs.org'
          scope: "@nayms"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install --force svm-rs && svm install "0.7.6" && svm install "0.8.13"

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Forge dependencies
        run: forge install

      - name: Build solidity contracts
        run: make build

      - name: Tests - local
        env:
          ALCHEMY_ETH_MAINNET_RPC_URL: ${{ secrets.ALCHEMY_ETH_MAINNET_RPC_URL }}
          ALCHEMY_ETH_GOERLI_RPC_URL: ${{ secrets.ALCHEMY_ETH_GOERLI_RPC_URL }}
        run: make tlocal

      # - name: Check gas snapshots on local tests
      #   run: forge snapshot --diff --gas-report --no-match-test testWithNaymsTokenCreateLiquidityPool

      # - name: Tests - mainnet fork
      #   run: forge t -f ${{secrets.ETH_HTTPS_URL_1}} --fork-block-number 15078000 --etherscan-api-key ${{secrets.ETHERSCAN_API_KEY}} --gas-report

      # - name: Gas snapshot diff (not via-ir, yet)
      #   run: forge snapshot --diff -f ${{secrets.ETH_HTTPS_URL_1}} --fork-block-number 15078000
      #   continue-on-error: true

      - name: Coverage report
        run: make coverage
        continue-on-error: true

      # - name: Coverage report from fork compiled via-ir
      #   run: forge coverage --report lcov -f ${{secrets.ETH_HTTPS_URL_1}} --fork-block-number 15078000 --via-ir 
      #   continue-on-error: true

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./lcov-filtered.info"
        if: always()
        continue-on-error: true

      # - name: Static analyser Slither (todo)
      #   uses: crytic/slither-action@v0.1.1
      #   id: slither
      #   continue-on-error: true
      #   with:
      #     sarif: results.sarif

      # - name: Upload Slither SARIF file
      #   uses: github/codeql-action/upload-sarif@v2
      #   continue-on-error: true
      #   with:
      #     sarif_file: ${{ steps.slither.outputs.sarif }}

      # - name: Static analyser Mythril (todo)
      #   run: mythril
      #   continue-on-error: true
          
      # - name: Publish to NPM
      #   run: yarn publish
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}