name: tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "yarn"
          registry-url: 'https://registry.npmjs.org'
          scope: "@nayms"

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install --force svm-rs && svm install "0.7.6" && svm install "0.8.13"

      - name: Install Foundry
        uses: onbjerg/foundry-toolchain@v1
        with:
          version: nightly

      - name: Install Forge dependencies
        run: forge install

      - name: Build solidity contracts
        run: make build

      - name: Tests - local
        run: make tlocal
