name: test
on:
  push:
    branches:
      - main
      - dev
  pull_request:
    branches:
      - dev

jobs:
  run-tests:
    name: Test contracts
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: read
      contents: read
      security-events: write
    env:
      ETH_MAINNET_RPC_URL: ${{ secrets.ETH_MAINNET_RPC_URL }}
      ETH_SEPOLIA_RPC_URL: ${{ secrets.ETH_SEPOLIA_RPC_URL }}
      BASE_MAINNET_RPC_URL: ${{ secrets.BASE_MAINNET_RPC_URL }}
      BASE_SEPOLIA_RPC_URL: ${{ secrets.BASE_SEPOLIA_RPC_URL }}
      AURORA_MAINNET_RPC_URL: ${{ secrets.AURORA_MAINNET_RPC_URL}}
      AURORA_TESTNET_RPC_URL: ${{ secrets.AURORA_TESTNET_RPC_URL}}
    timeout-minutes: 15
    container:
      image: ghcr.io/nayms/contracts-builder:latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: "yarn"

      - name: Install solc
        run: svm install 0.7.6 && svm install 0.8.24 && svm use 0.8.24

      - name: Fix ownership
        run: git config --global --add safe.directory /__w/contracts-v3/contracts-v3

      - name: Install Forge dependencies
        run: forge install

      - name: Install Node dependencies
        run: yarn

      - name: Build solidity contracts
        run: make build

      - name: Tests - local
        run: make test

      - name: Coverage report
        run: make coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./lcov-filtered.info"

      - name: Slither Static Analyser
        id: slither
        env:
          SOLC_VERSION: 0.8.24
        run: make slither

      - name: Upload Slither SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: results.sarif
