name: tests
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    # https://docs.github.com/en/actions/reference/authentication-in-a-workflow
    permissions:
      id-token: write
      packages: read
      contents: read
      security-events: write
    timeout-minutes: 15
    container:
      image: ghcr.io/nayms/contracts-builder:latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Update path
        run: echo "/root/.cargo/bin:/root/.foundry/bin" >> $GITHUB_PATH

      - name: Install solc
        run: svm install 0.7.6 && svm install 0.8.13 && svm use 0.8.13

      - name: Install Forge dependencies
        run: forge install

      - name: Install Node dependencies
        run: yarn

      - name: Prepare build
        run: make prep-build

      - name: Build solidity contracts
        run: make build

      - name: Tests - local
        env:
          ALCHEMY_ETH_MAINNET_RPC_URL: ${{ secrets.ALCHEMY_ETH_MAINNET_RPC_URL }}
          ALCHEMY_ETH_GOERLI_RPC_URL: ${{ secrets.ALCHEMY_ETH_GOERLI_RPC_URL }}
        run: make test

      # - name: Check gas snapshots on local tests
      #   run: forge snapshot --diff --gas-report --no-match-test testWithNaymsTokenCreateLiquidityPool

      # - name: Tests - mainnet fork
      #   run: forge t -f ${{secrets.ETH_HTTPS_URL_1}} --fork-block-number 15078000 --etherscan-api-key ${{secrets.ETHERSCAN_API_KEY}} --gas-report

      # - name: Gas snapshot diff (not via-ir, yet)
      #   run: forge snapshot --diff -f ${{secrets.ETH_HTTPS_URL_1}} --fork-block-number 15078000
      #   continue-on-error: true

      - name: Coverage report
        run: make coverage

      # - name: Coverage report from fork compiled via-ir
      #   run: forge coverage --report lcov -f ${{secrets.ETH_HTTPS_URL_1}} --fork-block-number 15078000 --via-ir
      #   continue-on-error: true

      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: "./lcov-filtered.info"

      - name: Slither Static Analyser
        uses: crytic/slither-action@v0.2.0
        id: slither
        with:
          sarif: results.sarif
          target: src/diamonds/nayms
          slither-args: --exclude solc-version,assembly-usage,naming-convention --ignore-compile
        continue-on-error: true

      - name: Upload Slither SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.slither.outputs.sarif }}

      # - name: Static analyser Mythril (todo)
      #   run: mythril
      #   continue-on-error: true
